const actionType = {
    PRODUCTSDATA: "PRODUCTSDATA",
    OPENHEADERMOUDLE: "OPENHEADERMOUDLE",
    OPENLOGINMOUDLE: "OPENLOGINMOUDLE",
    OPENSIGNINMOUDLE: "OPENSIGNINMOUDLE",
    SHOWMORETRENDING: "SHOWMORETRENDING",
    SINGLEPRODUCT: "SINGLEPRODUCT",
    SETCART: "SETCART",
    SETQNTY: "SETQNTY",
    REMOVEFOMCART: "REMOVEFOMCART",
    OPENSIDEBAR: "OPENSIDEBAR",
    SEARCHVALUE: "SEARCHVALUE",
    LOADING: "LOADING",
    LOGINUSERNAME: "LOGINUSERNAME",
    LOGINPASSWORD: "LOGINPASSWORD",
    SUBMITLOGININFO: "SUBMITLOGININFO",
    LOGIN: "LOGIN",
    SIGNUPUSERNAME: "SIGNUPINFO",
    SIGNUPEMAIL: "SIGNUPEMAIL",
    SIGNUPPASSWORD: "SIGNUPPASSWORD",
    SIGNUPUSERINFO: "SIGNUPUSERINFO",
    SIGNUPSTATUS: "SIGNUPSTATUS"
}
export default actionType;